"""job search intelligence and recommendations

Revision ID: 0cfd911f971d
Revises: b60fd5846734
Create Date: 2026-08-17 14:53:54.811265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '0cfd911f971d'
down_revision: Union[str, None] = 'b60fd5846734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # priority_level (Step 6) and remote_preference (Step 1) already
    # exist -- create_type=False so reusing them here doesn't try to
    # CREATE TYPE a name that's already in the database.
    priority_level = PGEnum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_level', create_type=False)
    remote_preference = PGEnum('REMOTE', 'HYBRID', 'ONSITE', 'FLEXIBLE', name='remote_preference', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_job_search_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('target_locations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('remote_preference', remote_preference, nullable=True),
    sa.Column('target_companies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('minimum_match_score', sa.Integer(), nullable=True),
    sa.Column('applications_per_week', sa.Integer(), nullable=True),
    sa.Column('interviews_per_month', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('employment_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOB_PRIORITY', 'JOB_SKIP', 'CV_IMPROVEMENT', 'SKILL_GAP', 'FOLLOWUP', 'INTERVIEW_PREPARATION', 'APPLICATION_STRATEGY', 'SOURCE_STRATEGY', 'CAREER_DIRECTION', 'REJECTION_PATTERN', 'GENERAL_INSIGHT', name='recommendation_type'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', priority_level, nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.Column('related_application_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'VIEWED', 'ACCEPTED', 'DISMISSED', 'COMPLETED', 'EXPIRED', name='recommendation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_type'), 'recommendations', ['type'], unique=False)

    # Unlike create_table (which auto-creates dependent enum types),
    # add_column on an EXISTING table does not -- rejection_reason is
    # brand new and must be created explicitly first, or the ALTER TABLE
    # fails with "type rejection_reason does not exist".
    rejection_reason = PGEnum(
        'NO_RESPONSE', 'INSUFFICIENT_EXPERIENCE', 'SKILLS_GAP', 'LOCATION', 'SALARY', 'SPONSORSHIP',
        'INTERNAL_CANDIDATE', 'POSITION_CLOSED', 'UNKNOWN', 'OTHER', name='rejection_reason', create_type=False,
    )
    rejection_reason.create(op.get_bind(), checkfirst=True)
    op.add_column('applications', sa.Column('rejection_reason', rejection_reason, nullable=True))
    op.add_column('applications', sa.Column('rejection_reason_custom', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'rejection_reason_custom')
    op.drop_column('applications', 'rejection_reason')
    op.drop_index(op.f('ix_recommendations_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('user_job_search_goals')
    # ### end Alembic commands ###
    PGEnum(name='rejection_reason').drop(op.get_bind(), checkfirst=True)
