"""job ingestion, analysis, and matching

Revision ID: 1e3229e0ffdb
Revises: b2ed68fa50f5
Create Date: 2026-08-14 17:14:21.818193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3229e0ffdb'
down_revision: Union[str, None] = 'b2ed68fa50f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY', 'UNKNOWN', name='job_employment_type'), nullable=True),
    sa.Column('workplace_type', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', 'UNKNOWN', name='workplace_type'), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('description_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'ANALYZED', 'MATCHED', 'SHORTLISTED', 'SKIPPED', name='job_status'), nullable=False),
    sa.Column('duplicate_of_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_canonical_url'), 'jobs', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_jobs_description_hash'), 'jobs', ['description_hash'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('APPLY', 'MAYBE', 'SKIP', name='recommendation'), nullable=False),
    sa.Column('matched_requirements', sa.JSON(), nullable=False),
    sa.Column('partial_requirements', sa.JSON(), nullable=False),
    sa.Column('missing_requirements', sa.JSON(), nullable=False),
    sa.Column('unknown_requirements', sa.JSON(), nullable=False),
    sa.Column('critical_gaps', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL_SKILL', 'SOFT_SKILL', 'EDUCATION', 'EXPERIENCE', 'CERTIFICATION', 'RESPONSIBILITY', 'LOCATION', 'WORK_AUTHORIZATION', 'LANGUAGE', 'OTHER', name='requirement_category'), nullable=False),
    sa.Column('importance', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='requirement_importance'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=True),
    sa.Column('years_required', sa.Float(), nullable=True),
    sa.Column('education_requirement', sa.String(length=500), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_requirements')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_jobs_description_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_url'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
