"""cv customization, versioning, and pdf generation

Revision ID: 5d0b7049cec3
Revises: 1e3229e0ffdb
Create Date: 2026-08-14 19:38:47.960251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '5d0b7049cec3'
down_revision: Union[str, None] = '1e3229e0ffdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # cv_section_type is used by both cv_changes.section and
    # cv_sections.section_type; entity_type already exists (created by the
    # Step 1 migration for evidence_links.entity_type). Create the shared
    # type explicitly once and reference it everywhere with
    # create_type=False, so the second column definition doesn't try to
    # CREATE TYPE a name that already exists.
    cv_section_type = PGEnum(
        'SUMMARY', 'SKILLS', 'EXPERIENCE', 'PROJECTS', 'RESEARCH', 'EDUCATION', 'CERTIFICATIONS', 'ACHIEVEMENTS',
        name='cv_section_type', create_type=False,
    )
    cv_section_type.create(op.get_bind(), checkfirst=True)
    entity_type = PGEnum(
        'SKILL', 'EDUCATION', 'EXPERIENCE', 'EXPERIENCE_BULLET', 'PROJECT', 'PROJECT_RESULT', 'RESEARCH',
        'CERTIFICATION', 'ACHIEVEMENT', name='entity_type', create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='cv_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('experience', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('research', sa.JSON(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('latex_source', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('match_score_before', sa.Integer(), nullable=True),
    sa.Column('match_score_after', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_version_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'REMOVED', 'REWRITTEN', 'REORDERED', 'EMPHASIZED', 'DE_EMPHASIZED', name='cv_change_type'), nullable=False),
    sa.Column('section', cv_section_type, nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('customized_text', sa.Text(), nullable=True),
    sa.Column('source_type', entity_type, nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cv_version_id'], ['cv_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_version_id', sa.Integer(), nullable=False),
    sa.Column('section_type', cv_section_type, nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cv_version_id'], ['cv_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_sections')
    op.drop_table('cv_changes')
    op.drop_table('cv_versions')
    # ### end Alembic commands ###
    PGEnum(name='cv_section_type').drop(op.get_bind(), checkfirst=True)
