"""browser application assistant

Revision ID: 67aedf5502cb
Revises: 75a3bd56227d
Create Date: 2026-08-16 22:28:15.347985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67aedf5502cb'
down_revision: Union[str, None] = '75a3bd56227d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cv_version_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('original_job_url', sa.String(length=1000), nullable=True),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('platform', sa.Enum('GENERIC', 'GREENHOUSE', 'LEVER', 'WORKDAY', 'LINKEDIN', 'INDEED', 'COMPANY_SITE', 'UNKNOWN', name='application_platform'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PREPARING', 'BROWSER_OPEN', 'FILLING', 'NEEDS_USER_INPUT', 'READY_FOR_REVIEW', 'APPROVED_FOR_SUBMISSION', 'SUBMITTING', 'SUBMITTED', 'FAILED', 'ABANDONED', 'BLOCKED', name='application_status'), nullable=False),
    sa.Column('submission_approved', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cv_version_id'], ['cv_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('APPLICATION_CREATED', 'BROWSER_OPENED', 'PAGE_LOADED', 'FIELD_DETECTED', 'FIELD_FILLED', 'FILE_UPLOADED', 'QUESTION_DETECTED', 'USER_INPUT_REQUIRED', 'REVIEW_READY', 'SUBMISSION_APPROVED', 'SUBMISSION_STARTED', 'SUBMISSION_COMPLETED', 'SUBMISSION_FAILED', 'BLOCKED', name='application_event_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('field_identifier', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'EMAIL', 'PHONE', 'NUMBER', 'DATE', 'SELECT', 'CHECKBOX', 'RADIO', 'FILE', 'ADDRESS', 'URL', 'UNKNOWN', name='application_field_type'), nullable=False),
    sa.Column('page_url', sa.String(length=1000), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('detected_value', sa.Text(), nullable=True),
    sa.Column('mapped_source', sa.String(length=255), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('final_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'MAPPED', 'FILLED', 'NEEDS_REVIEW', 'SKIPPED', 'REJECTED', name='application_field_status'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'ERROR', name='application_session_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_sessions')
    op.drop_table('application_fields')
    op.drop_table('application_events')
    op.drop_table('applications')
    # ### end Alembic commands ###
