"""cover letters and application question answers

Revision ID: 75a3bd56227d
Revises: 5d0b7049cec3
Create Date: 2026-08-16 20:58:20.284959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '75a3bd56227d'
down_revision: Union[str, None] = '5d0b7049cec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # cv_status already exists (created by the Step 3 migration for
    # cv_versions.status) and is reused here for cover_letters.status and
    # application_answers.status -- same identical draft/validated/
    # approved/rejected/archived workflow, so create_type=False on both
    # usages avoids a duplicate CREATE TYPE.
    cv_status = PGEnum('DRAFT', 'VALIDATED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='cv_status', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MOTIVATION', 'EXPERIENCE', 'TECHNICAL', 'BEHAVIORAL', 'COMPANY', 'SALARY', 'AVAILABILITY', 'RELOCATION', 'AUTHORIZATION', 'GENERAL', 'UNKNOWN', name='application_question_type'), nullable=False),
    sa.Column('character_limit', sa.Integer(), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('status', cv_status, nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['application_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cv_version_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', cv_status, nullable=False),
    sa.Column('source_evidence', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cv_version_id'], ['cv_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('career_profiles', sa.Column('salary_expectation', sa.String(length=255), nullable=True))
    op.add_column('career_profiles', sa.Column('work_authorization', sa.String(length=255), nullable=True))
    op.add_column('career_profiles', sa.Column('relocation_preference', sa.String(length=255), nullable=True))
    op.add_column('career_profiles', sa.Column('availability_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'availability_date')
    op.drop_column('career_profiles', 'relocation_preference')
    op.drop_column('career_profiles', 'work_authorization')
    op.drop_column('career_profiles', 'salary_expectation')
    op.drop_table('cover_letters')
    op.drop_table('application_answers')
    op.drop_table('application_questions')
    # ### end Alembic commands ###
