"""job search tracking analytics and follow-up management

Revision ID: b60fd5846734
Revises: 67aedf5502cb
Create Date: 2026-08-17 01:52:58.063864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = 'b60fd5846734'
down_revision: Union[str, None] = '67aedf5502cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# New JobStatus/ApplicationStatus/ApplicationEventType members added for
# Step 6 (see app/models/enums.py) -- these Postgres enum types already
# exist (created by earlier migrations), so new labels must be added with
# ALTER TYPE ... ADD VALUE rather than CREATE TYPE.
NEW_JOB_STATUS_VALUES = ('PREPARING', 'READY_TO_APPLY', 'APPLIED', 'WITHDRAWN', 'CLOSED', 'REJECTED', 'ARCHIVED')
NEW_APPLICATION_STATUS_VALUES = (
    'UNDER_REVIEW', 'RECRUITER_CONTACT', 'INTERVIEW', 'TECHNICAL_INTERVIEW', 'FINAL_INTERVIEW',
    'OFFER', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'GHOSTED', 'CLOSED',
)
NEW_APPLICATION_EVENT_TYPE_VALUES = (
    'DISCOVERED', 'ANALYZED', 'SHORTLISTED', 'CV_GENERATED', 'COVER_LETTER_GENERATED',
    'RECRUITER_CONTACT', 'FOLLOW_UP', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'ASSESSMENT',
    'OFFER_RECEIVED', 'REJECTION', 'WITHDRAWAL', 'NOTE_ADDED', 'STATUS_CHANGED',
)

# application_status_history.old_status/new_status both reference this
# already-existing type within the same migration; create_type=False on
# the shared object avoids a duplicate CREATE TYPE (same pattern as
# cv_section_type in the Step 3 migration).
APPLICATION_STATUS_VALUES = (
    'NOT_STARTED', 'PREPARING', 'BROWSER_OPEN', 'FILLING', 'NEEDS_USER_INPUT', 'READY_FOR_REVIEW',
    'APPROVED_FOR_SUBMISSION', 'SUBMITTING', 'SUBMITTED', 'FAILED', 'ABANDONED', 'BLOCKED',
) + NEW_APPLICATION_STATUS_VALUES


def upgrade() -> None:
    # --- Extend existing enum types with Step 6's new members -----------
    # ALTER TYPE ... ADD VALUE cannot run inside the same transaction that
    # later *uses* the new value in a comparison, but simply adding labels
    # (with nothing in this migration that queries against them) is safe
    # under Alembic's default transactional DDL on Postgres 12+.
    for value in NEW_JOB_STATUS_VALUES:
        op.execute(f"ALTER TYPE job_status ADD VALUE IF NOT EXISTS '{value}'")
    for value in NEW_APPLICATION_STATUS_VALUES:
        op.execute(f"ALTER TYPE application_status ADD VALUE IF NOT EXISTS '{value}'")
    for value in NEW_APPLICATION_EVENT_TYPE_VALUES:
        op.execute(f"ALTER TYPE application_event_type ADD VALUE IF NOT EXISTS '{value}'")

    # priority_level is brand new but reused across two columns
    # (applications.priority, jobs.priority) within this same migration --
    # create it explicitly once, then reference it with create_type=False
    # everywhere else.
    priority_level = PGEnum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_level', create_type=False)
    priority_level.create(op.get_bind(), checkfirst=True)

    application_status = PGEnum(*APPLICATION_STATUS_VALUES, name='application_status', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('RECRUITER_FOLLOWUP', 'APPLICATION_FOLLOWUP', 'INTERVIEW_FOLLOWUP', 'THANK_YOU', 'CUSTOM', name='followup_type'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='followup_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_followups_due_date'), 'application_followups', ['due_date'], unique=False)
    op.create_table('application_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('GENERAL', 'RECRUITER', 'INTERVIEW', 'TECHNICAL', 'FOLLOWUP', 'OFFER', 'REJECTION', name='application_note_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('old_status', application_status, nullable=True),
    sa.Column('new_status', application_status, nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RECRUITER', 'PHONE_SCREEN', 'TECHNICAL', 'BEHAVIORAL', 'HIRING_MANAGER', 'FINAL', 'OTHER', name='interview_type'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('meeting_url', sa.String(length=1000), nullable=True),
    sa.Column('interviewer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW', name='interview_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_scheduled_at'), 'interviews', ['scheduled_at'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'NEGOTIATING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='offer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('priority', priority_level, server_default='MEDIUM', nullable=False))
    op.add_column('applications', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('applications', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('applications', sa.Column('material_snapshot', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_priority'), 'applications', ['priority'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_submitted_at'), 'applications', ['submitted_at'], unique=False)
    op.add_column('job_matches', sa.Column('score_components', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('job_matches', sa.Column('algorithm_version', sa.String(length=20), server_default='v1', nullable=False))
    op.add_column('jobs', sa.Column('deadline_source', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('external_job_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('priority', priority_level, server_default='MEDIUM', nullable=False))
    op.add_column('jobs', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_external_job_id'), 'jobs', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_column('jobs', 'tags')
    op.drop_column('jobs', 'priority')
    op.drop_column('jobs', 'external_job_id')
    op.drop_column('jobs', 'deadline_source')
    op.drop_column('job_matches', 'algorithm_version')
    op.drop_column('job_matches', 'score_components')
    op.drop_index(op.f('ix_applications_submitted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_priority'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_column('applications', 'material_snapshot')
    op.drop_column('applications', 'archived')
    op.drop_column('applications', 'source')
    op.drop_column('applications', 'tags')
    op.drop_column('applications', 'priority')
    op.drop_table('offers')
    op.drop_index(op.f('ix_interviews_scheduled_at'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('application_status_history')
    op.drop_table('application_notes')
    op.drop_index(op.f('ix_application_followups_due_date'), table_name='application_followups')
    op.drop_table('application_followups')
    op.drop_table('job_notes')
    # ### end Alembic commands ###
    # Note: removing enum labels added via ALTER TYPE ... ADD VALUE is not
    # supported by Postgres without recreating the type, so those
    # additions (NEW_JOB_STATUS_VALUES / NEW_APPLICATION_STATUS_VALUES /
    # NEW_APPLICATION_EVENT_TYPE_VALUES) are intentionally left in place on
    # downgrade -- consistent with Postgres's own constraints, not a
    # decision this migration can undo.
    PGEnum(name='priority_level').drop(op.get_bind(), checkfirst=True)
