"""AI job search agent orchestrator

Revision ID: c7930607f732
Revises: 5adad9fa34fd
Create Date: 2026-08-18 23:21:01.033291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = 'c7930607f732'
down_revision: Union[str, None] = '5adad9fa34fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # priority_level (Step 6) already exists -- create_type=False so
    # reusing it here doesn't try to CREATE TYPE a name that's already
    # in the database.
    priority_level = PGEnum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_level', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PLANNING', 'RUNNING', 'WAITING_FOR_APPROVAL', 'WAITING_FOR_USER_INPUT', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='agent_task_status'), nullable=False),
    sa.Column('priority', priority_level, nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('final_result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'PLANNING_STARTED', 'PLAN_CREATED', 'TOOL_STARTED', 'TOOL_COMPLETED', 'TOOL_FAILED', 'APPROVAL_REQUESTED', 'APPROVAL_RECEIVED', 'USER_INPUT_REQUIRED', 'TASK_PAUSED', 'TASK_RESUMED', 'TASK_COMPLETED', 'TASK_FAILED', 'TASK_CANCELLED', name='agent_event_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tool', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_task_id'), 'agent_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_events_timestamp'), 'agent_events', ['timestamp'], unique=False)
    op.create_table('agent_plan_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('tool', sa.String(length=255), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_FOR_APPROVAL', 'SKIPPED', 'COMPLETED', 'FAILED', name='agent_plan_step_status'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_plan_steps_task_id'), 'agent_plan_steps', ['task_id'], unique=False)
    op.create_table('agent_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('plan_step_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_preview', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='agent_approval_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_step_id'], ['agent_plan_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_approvals_status'), 'agent_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_agent_approvals_task_id'), 'agent_approvals', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_approvals_task_id'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_status'), table_name='agent_approvals')
    op.drop_table('agent_approvals')
    op.drop_index(op.f('ix_agent_plan_steps_task_id'), table_name='agent_plan_steps')
    op.drop_table('agent_plan_steps')
    op.drop_index(op.f('ix_agent_events_timestamp'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_task_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
